### ISSUE TITLE
IAM role support is not working

### ISSUE THREAD

**Issue by guss77** [mirkokiefer/aws-lib#89]
According to the documentation, initializing the clients without key id and secret will cause the client to use the IAM role of the hosting EC2 machine for authentication. Unfortunately this does not work and when I try to instantiate a client with no parameters, I get the following error:

```
Uncaught TypeError: Not a buffer
  at new Hmac (crypto.js:226:17)
  at Object.Hmac (crypto.js:224:12)
  at Object.exports.hmacSha256 (/home/ubuntu/aws-lib/lib/utils.js:5:21)
  at signQuery (/home/ubuntu/aws-lib/lib/aws.js:166:18)
  at addQueryProperties (/home/ubuntu/aws-lib/lib/aws.js:121:34)
  at /home/ubuntu/aws-lib/lib/aws.js:71:15
  at /home/ubuntu/aws-lib/lib/metadata.js:59:9
  at IncomingMessage.<anonymous> (/home/ubuntu/aws-lib/lib/metadata.js:24:22)
  at IncomingMessage.EventEmitter.emit (events.js:117:20)
  at _stream_readable.js:910:16
  at process._tickCallback (node.js:415:13)
```

Also, when running the test without credentials, all the tests fail with this message.

**Comment by guss77** [comment]
ping? any chance of having the PR merged?
